# [aws]
# symbol = "  "
#
# [buf]
# symbol = " "
#
# [c]
# symbol = " "
#
# [conda]
# symbol = " "
#
# [crystal]
# symbol = " "
#
# [dart]
# symbol = " "
#
# [directory]
# read_only = " 󰌾"
#
# [docker_context]
# symbol = " "
#
# [elixir]
# symbol = " "
#
# [elm]
# symbol = " "
#
# [fennel]
# symbol = " "
#
# [fossil_branch]
# symbol = " "
#
# [git_branch]
# symbol = " "
#
# [git_commit]
# tag_symbol = '  '
#
# [golang]
# symbol = " "
#
# [guix_shell]
# symbol = " "
#
# [haskell]
# symbol = " "
#
# [haxe]
# symbol = " "
#
# [hg_branch]
# symbol = " "
#
# [hostname]
# ssh_symbol = " "
#
# [java]
# symbol = " "
#
# [julia]
# symbol = " "
#
# [kotlin]
# symbol = " "
#
# [lua]
# symbol = " "
#
# [memory_usage]
# symbol = "󰍛 "
#
# [meson]
# symbol = "󰔷 "
#
# [nim]
# symbol = "󰆥 "
#
# [nix_shell]
# symbol = " "
#
# [nodejs]
# symbol = " "
#
# [ocaml]
# symbol = " "
#
# [os.symbols]
# Alpaquita = " "
# Alpine = " "
# AlmaLinux = " "
# Amazon = " "
# Android = " "
# Arch = " "
# Artix = " "
# CentOS = " "
# Debian = " "
# DragonFly = " "
# Emscripten = " "
# EndeavourOS = " "
# Fedora = " "
# FreeBSD = " "
# Garuda = "󰛓 "
# Gentoo = " "
# HardenedBSD = "󰞌 "
# Illumos = "󰈸 "
# Kali = " "
# Linux = " "
# Mabox = " "
# Macos = " "
# Manjaro = " "
# Mariner = " "
# MidnightBSD = " "
# Mint = " "
# NetBSD = " "
# NixOS = " "
# OpenBSD = "󰈺 "
# openSUSE = " "
# OracleLinux = "󰌷 "
# Pop = " "
# Raspbian = " "
# Redhat = " "
# RedHatEnterprise = " "
# RockyLinux = " "
# Redox = "󰀘 "
# Solus = "󰠳 "
# SUSE = " "
# Ubuntu = " "
# Unknown = " "
# Void = " "
# Windows = "󰍲 "
#
# [package]
# symbol = "󰏗 "
#
# [perl]
# symbol = " "
#
# [php]
# symbol = " "
#
# [pijul_channel]
# symbol = " "
#
# [python]
# symbol = " "
#
# [rlang]
# symbol = "󰟔 "
#
# [ruby]
# symbol = " "
#
# [rust]
# symbol = "󱘗 "
#
# [scala]
# symbol = " "
#
# [swift]
# symbol = " "
#
# [zig]
# symbol = " "
#
# [gradle]
# symbol = " "


# NOTE: Seth Phaeno https://github.com/Sin-cy/dotfiles/blob/main/starship/.config/starship/starship.toml
# command_timeout = 1000
#
# "$schema" = 'https://starship.rs/config-schema.json'
#
# add_newline = false 
#
# format = """
#  ➜\
# $directory\
# ${custom.giturl}\
# $git_branch\
# $git_state\
# $git_status\
# $line_break\
# $character
# """
#
# right_format = """$all"""
#
# palette = "catppuccin_mocha"
#
# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"
#
# # [palettes.custom]
# # rosewater = "#f5e0dc"
# # flamingo = "#eb6f92"
# # pink = "#f5c2e7"
# # orange = "#cba6f7"
# # color_red = '#cc241d'
# # red = "#f38ba8"
# # maroon = "#eba0ac"
# # peach = "#fab387"
# # yellow = "#f9e2af"
# # green = "#a6e3a1"
# # teal = "#94e2d5"
# # sky = "#89dceb"
# # sapphire = "#74c7ec"
# # blue = "#89b4fa"
# # lavender = "#b4befe"
# # foam = "#9ccfd8"
# # pine = "#31748f"
# # gold = "#f6c177"
# # rose = "#ebbcba"
# # text = "#cdd6f4"
# # subtext1 = "#bac2de"
# # subtext0 = "#a6adc8"
# # overlay2 = "#9399b2"
# # overlay1 = "#7f849c"
# # overlay0 = "#6c7086"
# # surface2 = "#585b70"
# # surface1 = "#45475a"
# # surface0 = "#313244"
# # base = "#1e1e2e"
# # mantle = "#181825"
# # crust = "#11111b"
#
# [os.symbols]
# Windows = "󰍲"
# Ubuntu = "󰕈"
# SUSE = ""
# Raspbian = "󰐿"
# Mint = "󰣭"
# Macos = " "
# Manjaro = ""
# Linux = "󰌽"
# Gentoo = "󰣨"
# Fedora = "󰣛"
# Alpine = ""
# Amazon = ""
# Android = ""
# Arch = "󰣇"
# Artix = "󰣇"
# CentOS = ""
# Debian = "󰣚"
# Redhat = "󱄛"
# RedHatEnterprise = "󱄛"
#
# [username]
# #show_always = true
# #style_user = "bg:surface0 fg:text"
# #style_root = "bg:surface0 fg:text"
# #format = '[ $user ]($style)'
#
# [directory]
# style = "sapphire"
# format = "[ $path ]($style)"
# #truncation_length = 4
# #truncation_symbol = "…/"
#
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = "󰝚 "
# "Pictures" = " "
# "Developer" = "󰲋 "
#
# [os]
# disabled = true
# #style = "bg:surface0 fg:text"
#
# [custom.giturl]
# # disabled = true
# description = "Display symbol for remote Git server"
# command = """
# GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
# if [[ "$GIT_REMOTE" =~ "github" ]]; then
#     GIT_REMOTE_SYMBOL=" "
# elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
#     GIT_REMOTE_SYMBOL=" "
# elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
#     GIT_REMOTE_SYMBOL=" "
# elif [[ "$GIT_REMOTE" =~ "git" ]]; then
#     GIT_REMOTE_SYMBOL=" "
# else
#     GIT_REMOTE_SYMBOL=" "
# fi
# echo "$GIT_REMOTE_SYMBOL "
# """
# when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
# format = "at $output"
#
# [git_branch]
# symbol = "[](black) "
# # format =  ' [$symbol$branch(:$remote_branch)]($style)[]'
# style = "fg:lavender bg:black"
# format =  '  on [$symbol$branch]($style)[](black)'
#
# [git_status]
# format = ' [($all_status$ahead_behind )]($style)'
#
# [nodejs]
# symbol = ""
# format = '[ $symbol( $version) ]($style)'
#
# [c]
# symbol = " "
# format = '[[ $symbol( $version) ]]($style)'
#
# [rust]
# symbol = ""
# format = '[[ $symbol( $version) ]]($style)'
#
# [golang]
# symbol = ""
# format = '[ $symbol( $version) ]($style)'
# detect_files = ["go.mod"]
#
# [php]
# symbol = ""
# format = '[[ $symbol( $version) ]]($style)'
#
# [java]
# symbol = " "
# format = '[[ $symbol( $version) ]]($style)'
#
# [kotlin]
# symbol = ""
#
# format = '[[ $symbol( $version) ]]($style)'
#
# [haskell]
# symbol = ""
#
# format = '[[ $symbol( $version) ]]($style)'
#
# [python]
# symbol = ""
#
# format = '[[ $symbol( $version) ]]($style)'
#
#
# [docker_context]
# symbol = ""
# format = '[ $symbol( $context) ]($style)'
#
#
# [time]
# disabled = true
# time_format = "%R"
# style = "bg:peach"
# format = '[[  $time ](fg:mantle bg:foam)]($style)'
#
# [line_break]
# disabled = true 
#
# [character]
# disabled = false
# success_symbol = '[𝘹](bold fg:green)'
# error_symbol = '[𝘹](bold fg:red)'
# vimcmd_symbol = '[](bold fg:creen)'
# vimcmd_replace_one_symbol = '[](bold fg:purple)'
# vimcmd_replace_symbol = '[](bold fg:purple)'
# vimcmd_visual_symbol = '[](bold fg:lavender)'

# NOTE: catppuccin_mocha
# "$schema" = 'https://starship.rs/config-schema.json'
#
# format = """
# [](surface0)\
# $os\
# $username\
# [](bg:peach fg:surface0)\
# $directory\
# [](fg:peach bg:green)\
# $git_branch\
# $git_status\
# [](fg:green bg:teal)\
# $c\
# $rust\
# $golang\
# $nodejs\
# $php\
# $java\
# $kotlin\
# $haskell\
# $python\
# [](fg:teal bg:blue)\
# $docker_context\
# [](fg:blue bg:purple)\
# $time\
# [ ](fg:purple)\
# $line_break$character"""
#
# palette = 'catppuccin_mocha'
#
# [palettes.gruvbox_dark]
# color_fg0 = '#fbf1c7'
# color_bg1 = '#3c3836'
# color_bg3 = '#665c54'
# color_blue = '#458588'
# color_aqua = '#689d6a'
# color_green = '#98971a'
# color_orange = '#d65d0e'
# color_purple = '#b16286'
# color_red = '#cc241d'
# color_yellow = '#d79921'
#
# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# orange = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"
#
# [os]
# disabled = false
# style = "bg:surface0 fg:text"
#
# [os.symbols]
# Windows = "󰍲"
# Ubuntu = "󰕈"
# SUSE = ""
# Raspbian = "󰐿"
# Mint = "󰣭"
# Macos = " "
# Manjaro = ""
# Linux = "󰌽"
# Gentoo = "󰣨"
# Fedora = "󰣛"
# Alpine = ""
# Amazon = ""
# Android = ""
# Arch = "󰣇"
# Artix = "󰣇"
# CentOS = ""
# Debian = "󰣚"
# Redhat = "󱄛"
# RedHatEnterprise = "󱄛"
#
# [username]
# show_always = true
# style_user = "bg:surface0 fg:text"
# style_root = "bg:surface0 fg:text"
# format = '[ $user ]($style)'
#
# [directory]
# style = "fg:mantle bg:peach"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = "󰝚 "
# "Pictures" = " "
# "Developer" = "󰲋 "
#
# [git_branch]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol $branch ](fg:base bg:green)]($style)'
#
# [git_status]
# style = "bg:teal"
# format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [c]
# symbol = " "
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [rust]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [golang]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [php]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [java]
# symbol = " "
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [kotlin]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [haskell]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [python]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [docker_context]
# symbol = ""
# style = "bg:mantle"
# format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
#
# [time]
# disabled = false
# time_format = "%R"
# style = "bg:peach"
# format = '[[  $time ](fg:mantle bg:purple)]($style)'
#
# [line_break]
# disabled = false
#
# [character]
# disabled = false
# success_symbol = '[](bold fg:green)'
# error_symbol = '[](bold fg:red)'
# vimcmd_symbol = '[](bold fg:creen)'
# vimcmd_replace_one_symbol = '[](bold fg:purple)'
# vimcmd_replace_symbol = '[](bold fg:purple)'
# vimcmd_visual_symbol = '[](bold fg:lavender)'
# "$schema" = 'https://starship.rs/config-schema.json'
#
# format = """
# [](surface0)\
# $os\
# $username\
# [](bg:peach fg:surface0)\
# $directory\
# [](fg:peach bg:green)\
# $git_branch\
# $git_status\
# [](fg:green bg:teal)\
# $c\
# $rust\
# $golang\
# $nodejs\
# $php\
# $java\
# $kotlin\
# $haskell\
# $python\
# [](fg:teal bg:blue)\
# $docker_context\
# [](fg:blue bg:purple)\
# $time\
# [ ](fg:purple)\
# $line_break$character"""
#
# palette = 'catppuccin_mocha'
#
# [palettes.gruvbox_dark]
# color_fg0 = '#fbf1c7'
# color_bg1 = '#3c3836'
# color_bg3 = '#665c54'
# color_blue = '#458588'
# color_aqua = '#689d6a'
# color_green = '#98971a'
# color_orange = '#d65d0e'
# color_purple = '#b16286'
# color_red = '#cc241d'
# color_yellow = '#d79921'
#
# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# orange = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"
#
# [os]
# disabled = false
# style = "bg:surface0 fg:text"
#
# [os.symbols]
# Windows = "󰍲"
# Ubuntu = "󰕈"
# SUSE = ""
# Raspbian = "󰐿"
# Mint = "󰣭"
# Macos = " "
# Manjaro = ""
# Linux = "󰌽"
# Gentoo = "󰣨"
# Fedora = "󰣛"
# Alpine = ""
# Amazon = ""
# Android = ""
# Arch = "󰣇"
# Artix = "󰣇"
# CentOS = ""
# Debian = "󰣚"
# Redhat = "󱄛"
# RedHatEnterprise = "󱄛"
#
# [username]
# show_always = true
# style_user = "bg:surface0 fg:text"
# style_root = "bg:surface0 fg:text"
# format = '[ $user ]($style)'
#
# [directory]
# style = "fg:mantle bg:peach"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = "󰝚 "
# "Pictures" = " "
# "Developer" = "󰲋 "
#
# [git_branch]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol $branch ](fg:base bg:green)]($style)'
#
# [git_status]
# style = "bg:teal"
# format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [c]
# symbol = " "
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [rust]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [golang]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [php]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [java]
# symbol = " "
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [kotlin]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [haskell]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [python]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'
#
# [docker_context]
# symbol = ""
# style = "bg:mantle"
# format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
#
# [time]
# disabled = false
# time_format = "%R"
# style = "bg:peach"
# format = '[[  $time ](fg:mantle bg:purple)]($style)'
#
# [line_break]
# disabled = false
#
# [character]
# disabled = false
# success_symbol = '[](bold fg:green)'
# error_symbol = '[](bold fg:red)'
# vimcmd_symbol = '[](bold fg:creen)'
# vimcmd_replace_one_symbol = '[](bold fg:purple)'
# vimcmd_replace_symbol = '[](bold fg:purple)'
# vimcmd_visual_symbol = '[](bold fg:lavender)'
add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
