# Colors (flexoki-light)

[colors.bright]
black = '#575653'
blue = '#4385be'
cyan = '#3aa99f'
green = '#879a39'
magenta = '#ce5d97'
red = '#d14d41'
white = '#fffcf0'
yellow = '#d0a215'

[colors.cursor]
cursor = '#100f0f'
text = '#fffcf0'

[colors.normal]
black = '#100f0f'
blue = '#205ea6'
cyan = '#24837b'
green = '#66800b'
magenta = '#a02f6f'
red = '#af3029'
white = '#f2f0e5'
yellow = '#ad8301'

[colors.primary]
background = '#fffcf0'
foreground = '#100f0f'

[colors.selection]
background = '#cecdc3'
text = '#100f0f'
