# Colors (rose-pine)

[colors.bright]
black = '#6e6a86'
blue = '#31748f'
cyan = '#ebbcba'
green = '#9ccfd8'
magenta = '#c4a7e7'
red = '#eb6f92'
white = '#e0def4'
yellow = '#f6c177'

[colors.cursor]
cursor = '#e0def4'
text = '#191724'

[colors.normal]
black = '#26233a'
blue = '#31748f'
cyan = '#ebbcba'
green = '#9ccfd8'
magenta = '#c4a7e7'
red = '#eb6f92'
white = '#e0def4'
yellow = '#f6c177'

[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.selection]
background = '#191724'
text = '#e0def4'
